openai_api_key = "your-api-key-here"

anthropic_api_key = "your-other-api-key-her"
anthropic_model_name = "claude-3-haiku-20240307"

# Used for OpenAI and Claude LLMs. You can say things like:
# "Anwser every question like you are Elvis."
#   or 
# "output your answer in valid JSON"
system_prompt = ""
